### PR TITLE
Unit tests on login component, configuration of test framework

### PR DESCRIPTION
**Pull request by idacaesar**
Pull Request: All Unit Tests Passed
I've completed and passed all unit tests for the login functionality. The tests cover the following aspects:

Displays all parts of the login form
Allows user to input username
Allows user to input password
Sends login credentials when form is submitted
Requires both username and password fields to be filled

- Configured react testing library 
- Added initial test for login component

This PR is ready for review.

### CODE REVIEW

**Comment by Fannynystrom** [comment]
Testet går inte igenom, se rad:
Error: src/tests/LoginComponent.test.tsx(1,1): error TS6133: 'React' is declared but its value is never read.

**Comment by Fannynystrom** [comment]
skriv också en beskrivning

**Comment by idacaesar** [comment]
> Testet går inte igenom, se rad: Error: src/tests/LoginComponent.test.tsx(1,1): error TS6133: 'React' is declared but its value is never read.

**Comment by idacaesar** [comment]
Gör en ny pull request för att säkerställa att .env filen inte kommer med då vi har gjort nya ändringar

**Pull request closed without merging**
